[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "objdict"
version = "0.0.1"
authors = [
  { name="Daniel Farayola", email="faradaydanfard@gmail.com" },
]
description = "An object wrapper for dict that allows for using object type notation with dictionaries."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hephhay/objdict.git"
"Bug Tracker" = "https://github.com/hephhay/objdict.git/issues"